#!/bin/bash
# Uasge:
#   sh barcode_fastq_gz_2_10xg_raw.sh barcoded.fastq \
#                                     sample_S1_L001_R1_001.fastq \
#                                     sample_S2_L001_R2_001.fastq
#
# Paramters:
#   $1 refer to reads generated by longranger basic command
#   $2 is read1 in 10x genomics raw reads format
#   $3 is read2 in 10x genomics raw reads format
#
# Warning :
#   this scrip always append into $2 and $3 if thoes file already exist.

awk   -F "BX:Z:"  '{ if(FNR%4==1){if($2!="") barcode=substr($2,0,16);else barcode="NNNNNNNNNNNNNNNN"}  if(FNR%8==1) printf("%s 1:N:0:0\n", $1) >> read1 ; else if(FNR%8==2) printf("%sNNNNNNN%s\n",barcode,$1) >>read1;else if (FNR%8==3) print $1 >> read1 ; else if (FNR%8==4) printf("KKKKKKKKKKKKKKKKKKKKKKK%s\n",$1) >>read1; else if (FNR%8==5) printf("%s 3:N:0:0\n", $1) >>read2; else print $1 >>read2; }'  read1=$2 read2=$3  $1
